namespace Core.Sql.Models;

/// <summary>
/// Attribute to map a class property to a specific SQL column name.
/// Use this when the property name differs from the database column name.
/// </summary>
/// <remarks>
/// Example usage:
/// <code>
/// public class User
/// {
///     [CustomDataSet("user_id")]
///     public int UserId { get; set; }
///     
///     [CustomDataSet("full_name")]
///     public string FullName { get; set; }
/// }
/// </code>
/// </remarks>
[AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
public class CustomDataSetAttribute : Attribute
{
    /// <summary>
    /// The SQL column name to map to this property.
    /// </summary>
    public string ColumnName { get; }

    /// <summary>
    /// Optional: Indicates if this column should be ignored during mapping.
    /// </summary>
    public bool Ignore { get; set; } = false;

    /// <summary>
    /// Optional: Default value if the column is DBNull.
    /// </summary>
    public object? DefaultValue { get; set; }

    /// <summary>
    /// Optional: Custom date format for DateTime parsing.
    /// </summary>
    public string? DateFormat { get; set; }

    /// <summary>
    /// Creates a new CustomDataSetAttribute with the specified column name.
    /// </summary>
    /// <param name="columnName">The database column name to map to.</param>
    public CustomDataSetAttribute(string columnName)
    {
        ColumnName = columnName ?? throw new ArgumentNullException(nameof(columnName));
    }

    /// <summary>
    /// Creates a new CustomDataSetAttribute that ignores the property.
    /// </summary>
    public CustomDataSetAttribute()
    {
        ColumnName = string.Empty;
        Ignore = true;
    }
}

/// <summary>
/// Attribute to mark a property as the primary key column.
/// </summary>
[AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
public class SqlPrimaryKeyAttribute : Attribute
{
    /// <summary>
    /// Indicates if the primary key is auto-generated (identity/auto_increment).
    /// </summary>
    public bool IsAutoGenerated { get; set; } = true;
}

/// <summary>
/// Attribute to mark a property as computed/generated by the database.
/// These properties will be excluded from INSERT/UPDATE operations.
/// </summary>
[AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
public class SqlComputedAttribute : Attribute
{
}
